default:
  latitude: -29.6846
  longitude: -51.1419
  log_file: "weather_logs.log"
  log_level: "INFO"
  kinesis_stream_name: "broker"  # Nome do stream do Kinesis
  kinesis_region: "us-east-1"    # Região do Kinesis (ex: us-east-1)

development:
  log_level: "DEBUG"
  kinesis_stream_name: "broker"
  kinesis_region: "us-east-1" 

production:
  log_level: "INFO"
  kinesis_stream_name: "broker"
  kinesis_region: "us-east-1" 