name: Deploy Lambda
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout código
        uses: actions/checkout@v3

      # Configuração do Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Criar ambiente virtual e instalar dependências
      - name: Configurar ambiente virtual e instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flake8 bandit pytest -r requirements.txt

      # Verificar qualidade do código com flake8
      - name: Verificar qualidade do código
        run: |
          source venv/bin/activate
          flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics

      # Executar testes com pytest
      - name: Executar testes
        run: |
          source venv/bin/activate
          pytest tests/

      # Configurar credenciais AWS
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Empacotar aplicação
      - name: Empacotar aplicação
        run: |
          mkdir package
          pip install -r requirements.txt -t package/
          cp lambda_function.py package/
          cp -r config package/
          cp -r src package/
          cd package
          zip -r9 ../lambda_function.zip .

      # Fazer upload do zip para o S3
      - name: Upload para S3
        run: |
          aws s3 cp lambda_function.zip s3://${{ secrets.AWS_LAMBDA_S3_BUCKET }}/${{ secrets.AWS_LAMBDA_S3_KEY }}


      # Fazer deploy na AWS Lambda usando S3
      - name: Fazer deploy na AWS Lambda
        run: |
          aws lambda update-function-code \
          --function-name real-time-data-engineer-lambda \
          --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET }} \
          --s3-key ${{ secrets.AWS_LAMBDA_S3_KEY }} \
          --publish